FROM amazoncorretto:8-alpine-jdk
COPY target/dodgygeezers-1.0-SNAPSHOT-allinone.jar /dodgygeezers-1.0-SNAPSHOT-allinone.jar
CMD ["/usr/bin/java", "-cp", "/dodgygeezers-1.0-SNAPSHOT-allinone.jar", "Main"]