FROM amazoncorretto:8-alpine-jdk
COPY target/girlsallowed-1.0-SNAPSHOT-allinone.jar /girlsallowed-1.0-SNAPSHOT-allinone.jar
CMD ["/usr/bin/java", "-cp", "/girlsallowed-1.0-SNAPSHOT-allinone.jar", "Main"]